version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    volumes:
      - ./mysql-init.sql:/tmp/mysql-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rdcoursemanagementplatformdb
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3307"
    restart: always
    networks:
      - default

  app:
    restart: always
    build: .
    volumes:
#      - .:.
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean install spring-boot:run
    depends_on:
      - mysql
    networks:
      - default

networks:
 default:

